### PR TITLE
First pass of cleanup

### PR DESCRIPTION
**Pull request by pdehaan**
@mwobensmith Still needs some testing before you merge.

You'll also need Nodejs and Bower installed.
Then run `bower install` to download and copy the Forge and Chart.js dependencies into "js/vendor", and currently you'll need to go into the "js/vendor/forge" directory and run `npm install && npm run minify` to generate the minified forge.min.js file. I'll try and think of a way to make that a bit smoother.

If you have ESLint installed, you can run `eslint .` and currently get about 58 errors/warnings which we'll need to investigate. I'll also need to enable the rules for indenting and single-vs-double quotes for consistency.

### CODE REVIEW

**Comment by pdehaan** [comment]
ESLint warnings are currently:
```
➜  ssl_compat git:(cleanup) eslint .

/Users/pdehaan/dev/github/ssl_compat/js/Data.js
   76:9   error  "temp" is already defined              no-redeclare
   82:20  error  "returnColorArray" is not defined      no-undef
   83:12  error  "i" is already defined                 no-redeclare
   90:31  error  "arg2" is defined but never used       no-unused-vars
   99:30  error  "arg2" is defined but never used       no-unused-vars
  108:30  error  "arg2" is defined but never used       no-unused-vars
  137:42  error  "fieldName" is defined but never used  no-unused-vars

/Users/pdehaan/dev/github/ssl_compat/js/IndexPage.js
   93:7   error  "currentTab" is defined but never used  no-unused-vars
  141:3   error  "ctx2" is not defined                   no-undef
  143:7   error  "myPieChart" is defined but never used  no-unused-vars
  143:30  error  "ctx2" is not defined                   no-undef

/Users/pdehaan/dev/github/ssl_compat/js/TLSCanary.js
   45:43  error  "e" is defined but never used           no-unused-vars
  144:3   error  "ctx2" is not defined                   no-undef
  146:7   error  "myPieChart" is defined but never used  no-unused-vars
  146:30  error  "ctx2" is not defined                   no-undef
  240:46  error  "arg" is defined but never used         no-unused-vars
  246:45  error  "arg" is defined but never used         no-unused-vars
  259:9   error  "url" is already defined                no-redeclare
  364:20  error  "Tab" is not defined                    no-undef

/Users/pdehaan/dev/github/ssl_compat/js/TabContainer.js
   12:35  error  "callback" is defined but never used  no-unused-vars
   76:56  error  "index" is defined but never used     no-unused-vars
   79:15  error  Empty block statement                 no-empty
   86:47  error  "index" is defined but never used     no-unused-vars
  147:14  error  Empty block statement                 no-empty

/Users/pdehaan/dev/github/ssl_compat/js/URIGrid.js
    9:21  error  "decodeEntities" is not defined       no-undef
   39:62  error  "pageSize" is defined but never used  no-unused-vars
   40:7   error  "tempList" is defined but never used  no-unused-vars
   84:7   error  "o" is defined but never used         no-unused-vars
  120:7   error  "o" is defined but never used         no-unused-vars
  132:9   error  "id" is already defined               no-redeclare

/Users/pdehaan/dev/github/ssl_compat/js/Utility.js
  17:35  error  "nodes" is defined but never used             no-unused-vars
  25:10  error  "decodeEntities" is defined but never used    no-unused-vars
  43:10  error  "returnColorArray" is defined but never used  no-unused-vars

/Users/pdehaan/dev/github/ssl_compat/scan_url.js
   31:6   error  "arguments" is not defined            no-undef
   31:19  error  "arguments" is not defined            no-undef
   62:5   error  "rank" is defined but never used      no-unused-vars
   63:5   error  "run_id" is defined but never used    no-unused-vars
   66:16  error  "arguments" is not defined            no-undef
   68:7   error  "arguments" is not defined            no-undef
   70:25  error  "arguments" is not defined            no-undef
   72:7   error  "arguments" is not defined            no-undef
   74:12  error  "arguments" is not defined            no-undef
   76:7   error  "arguments" is not defined            no-undef
   78:12  error  "arguments" is not defined            no-undef
   80:7   error  "arguments" is not defined            no-undef
   82:17  error  "arguments" is not defined            no-undef
   89:7   error  "arguments" is not defined            no-undef
   91:16  error  "arguments" is not defined            no-undef
   93:7   error  "arguments" is not defined            no-undef
   95:18  error  "arguments" is not defined            no-undef
   97:7   error  "arguments" is not defined            no-undef
   99:14  error  "arguments" is not defined            no-undef
  113:12  error  "i" is already defined                no-redeclare
  408:67  error  "callback" is defined but never used  no-unused-vars
  452:19  error  "req" is not defined                  no-undef
  474:7   error  "dump" is not defined                 no-undef
  568:5   error  "dump" is not defined                 no-undef
  573:3   error  "dump" is not defined                 no-undef

✖ 58 problems (58 errors, 0 warnings)
```

**Comment by pdehaan** [comment]
I also murdered v1_archive which is why the diff is so big. It's always in your Git history if you need those files. Or, you can create a new branch and dump the v1 files in there and keep them out of master.

**Comment by pdehaan** [comment]
But this seems like an awesome tool.
I think it took me about 13 minutes to do a run last night.
The CLI output seemed a bit quiet, so I was never sure if it was working in the background or stalled.
Since i already have Release/Beta/Nightly installed, it may be nice to have an option to point at existing binaries instead of downloading new ones on each run and making me drag-n-drop them into my Applications folder.

Not sure if you want to convert this somewhat to a Node.js app or something so you can do some fancy routes and templating since it looks like we have the index.htm file in at least 20 places.

**Comment by mwobensmith** [comment]
Incredible feedback! Thank you Peter. Give me a few days to get back on this and I'll start addressing these issues one by one. So very much appreciated!

**Comment by pdehaan** [comment]
No rush on feedback, I may be able to clean up a few more things by running the code through some auto formatter too to normalize all the single vs double quotes, etc. But that can be a future PR.

I think the first thing to do before making this public is to try and remove as many of the `eval()` statements as possible.

**Comment by pdehaan** [comment]
I may be able to experiment with converting this into a Node Express/Hapi server separately. That would remove a bunch of the HTML template duplication.

**Pull request merged**
